### ISSUE TITLE
Support remove redundant close brackets?

### ISSUE THREAD

**Issue by vagusX** [josdejong/jsonrepair#103]
![image](https://github.com/josdejong/jsonrepair/assets/6828924/194ee6d8-b4fe-4536-853f-fe4dfbb8323a)

related to https://github.com/josdejong/jsonrepair/issues/88#issuecomment-1434302464

**Comment by vagusX** [comment]
After debug locally, already support this feature?

![image](https://github.com/josdejong/jsonrepair/assets/6828924/8e49eea5-d1fa-47cf-a273-d139eaf5f336)

**Comment by josdejong** [comment]
Implemented in v3.3.0 now via f81ffad5f30fc7e3cec8f1481f8b189c6a4eb49f.
