### ISSUE TITLE
throwInvalidUnicodeCharacter loops forever if input ends with part of unicode char

### ISSUE THREAD

**Issue by daviderenger** [josdejong/jsonrepair#109]
This happened for me pretty frequently when parsing streaming result from chatGPT and it ends with one half emoji. Easy to test with:

const testString = '{"s \\ud';

Suggested solution:

```
function throwInvalidUnicodeCharacter(start: number) {
  let end = start + 2;
  const maxUnicodeLength = 6;  // Maximum length of Unicode escape sequences

  while (end - start <= maxUnicodeLength && /\w/.test(text[end])) {
    end++;
  }

  const chars = text.slice(start, end);
  throw new JSONRepairError(`Invalid unicode character "${chars}"`, i);
}
```

Or something similar

**Comment by josdejong** [comment]
Thanks for reporting, that `while` loop is indeed missing a check to stop after 6 characters.

I've fixed this in `jsonrepair@3.4.1` by adding some code to fix truncated unicode characters by removing the partial unicode character when located at the end of the input.
