### ISSUE TITLE
Adding missing escape for double quote not working

### ISSUE THREAD

**Issue by lerman01** [josdejong/jsonrepair#114]
I have the following JSON: 
`{
    "text": "I want to buy 65" television"
}`

I would expect that the output will be:
`{
    "text": "I want to buy 65\\" television"
}`

however in the playground im getting the following error: 
`Colon expected at position 45`

**Comment by josdejong** [comment]
Thanks for your input. It would be nice to improve the library further with repairing missing escape characters and finding the right end quote of such a string with unescaped quotes. For example `{ 'text': 'I want to buy 65" television' }` is correctly repaired.

Help would be welcome.
