### ISSUE TITLE
Missing types definition

### ISSUE THREAD

**Issue by jarodium** [josdejong/jsonrepair#115]
Hello

I am attempting to install types in my TS app using npm install --save-dev @types/jsonrepair but I am facing the following issue:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fjsonrepair - Not found
npm ERR! 404
npm ERR! 404  '@types/jsonrepair@*' is not in this registry.

Am I doing something wrong?

**Comment by jarodium** [comment]
@josdejong I see.

Thank you for the reply. 
I will suppress errors then.

**Comment by jarodium** [comment]
First I will give you more context.
I am using json repair from an aws lambda layer that will serve a lambda function, made in typescript.
Since the package is being included as a shared layer, the main lambda function does not need to include this package.

Now, when I build the function with npx tsc, typescript will complain about the missing types since I don't need to include the package, thus giving the error complaining that it can no longer find the types. So, by using npm install --save-dev @types/jsonrepair I was hoping to install the types only.

The error npx tsc gives me are similar to the ones it's being reported here: https://bobbyhadz.com/blog/typescript-cannot-find-type-definition-file-for-node

Most "literature" refers as a solution that the types but be added to this repo: https://github.com/DefinitelyTyped/DefinitelyTyped and npm install --save-dev @types/Libname will be picked up.

**Comment by josdejong** [comment]
And can't you simply do `npm install --save-dev jsonrepair` instead of `npm install --save-dev @types/jsonrepair`, since that is the package that contains the types? Or copy the type definition yourself alongside the output of your `npx tsc`?

**Comment by jarodium** [comment]
Haven't tried `npm install --save-dev jsonrepair`. Copy the type definition, i'm not sure if I understood correctly. You mean I should create in the tsconfig file the types from jsonrepair?

**Comment by josdejong** [comment]
I'm not familiar with your setup so I'm just sharing some general ideas. You can probably copy the types from the library to some place in your project or so. Or create your own file with the type definitions, if your setup is not able to automatically retrieve them from the `jsonrepair` library.

The type definitions of the library are not that complex, this is it 😉:

```ts
export type jsonrepair = (text: string) => string
```
