### ISSUE TITLE
two or more commas in a string breaks parsing

### ISSUE THREAD

**Issue by daviderenger** [josdejong/jsonrepair#121]
This is working:

{"translatedText":"I've Testing a bit, testing more comma

But this is not working:

{"translatedText":"I've Testing a bit, testing more commas, Not working

Error is: "Colon expected at position 58"

Use case is streaming tool call from chatGPT

**Comment by josdejong** [comment]
Thanks for reporting. It would be nice to improve on this, fixing truncated text.

I think a fix will most likely fix both #117 and this one (#121) in one go.

**Comment by daviderenger** [comment]
Do you think you will have time to look into this soonish?
If not I can take a look to see if I can solve it!

**Comment by josdejong** [comment]
Thanks! I want to look into it Wednesday to at least see what what is needed to solve this. If it's easy I can implement a solution rightaway, and if not I will report here.

**Comment by josdejong** [comment]
Ok I think I can work something out. It will be a compromise, letting jsonrepair better handle truncated strings (which is a very common case) over a few more obscure cases.

**Comment by josdejong** [comment]
Fixed now in `v3.6.1`. 

It wasn't a compromise in the end, just an improvement :)

**Comment by daviderenger** [comment]
Great! Good job :clap: 

Will test this asap

**Comment by daviderenger** [comment]
Works perfectly!

**Comment by josdejong** [comment]
Thanks, good to hear 🎉
