### ISSUE TITLE
python sdk?

### ISSUE THREAD

**Issue by yuanjie-ai** [josdejong/jsonrepair#124]
python sdk?

**Comment by tybalex** [comment]
I don't think the python code from issue84 works as expected, for example:
```
x = '{"name": "John", "age": no"}'
repaired_json = JsonRepair(x).repair()
print(repaired_json)
```
gives me this error: `Error: string index out of range`.
while jsonrepair will fix it to `{"name": "John", "age": "no"}`

**Comment by josdejong** [comment]
Hm... so there is work to do there.

Maybe this can work via [`js2py`](https://github.com/PiotrDabkowski/Js2Py/issues/324)? I tried it out but the library doesn't support python 3.12 unfortunately and throws errors. See https://github.com/PiotrDabkowski/Js2Py/issues/324.

**Comment by josdejong** [comment]
I found [PythonMonkey](https://github.com/Distributive-Network/PythonMonkey#pythonmonkey) and that works like a charm:

1. First, install the npm package in your project via `npm install jsonrepair`
2. Install `PythonMonkey` via `pip install pythonmonkey`
3. Use the libraries in a python script":
    
    ```python
    import pythonmonkey

    jsonrepair = pythonmonkey.require('jsonrepair').jsonrepair
    
    json = "{name: 'John'}"
    repaired = jsonrepair(json)
    print(repaired) 
    # {"name": "John"}
    ```

**Comment by tybalex** [comment]
@josdejong yep this works!

**Comment by josdejong** [comment]
That's cool 😎 .

I've added a section in the readme describing how to use `jsonrepair` in Python: https://github.com/josdejong/jsonrepair?tab=readme-ov-file#python

I think this more or less removes the need for a Python port (unless it turns out to have performance issues or other limitations). Closing this issue now.

**Comment by emanuelevivoli** [comment]
This is just amazing! Thanks, for all the effort <3

**Comment by josdejong** [comment]
👍 

Someone is also working on a Python port of the library, see: https://github.com/SelectedSolutionManagement/jsonrepair (as far as I know it's not yet published at pypi).
