### ISSUE TITLE
A failure case

### ISSUE THREAD

**Issue by gopricy** [josdejong/jsonrepair#133]
```{"images":[{"prompt":"girl, falling, shocked expression","seed":9827318951},{"prompt":"sticker, smiling, hello, falling","seed":2873720893},{"prompt":"girls, hugging, happy, shocked girl falling back,"seed":1831920181}]}```

I assume this broken-json aligns with the library's capability that one double quote is missing:

```{"images":[{"prompt":"girl, falling, shocked expression","seed":9827318951},{"prompt":"sticker, smiling, hello, falling","seed":2873720893},{"prompt":"girls, hugging, happy, shocked girl falling back","seed":1831920181}]}```

however, it throws an error
```Colon expected at position 166```

**Comment by josdejong** [comment]
Fixed now via 1899f70. 

There is one similar case that isn't solved: when the value with the missing end quote is the last in the object, like `{a:"b,c,}`. In that case `jsonrepair` still throws an error. If that case occurs in practice please open a new issue, that will be harder to address.
