### ISSUE TITLE
Nodejs?

### ISSUE THREAD

**Issue by colo13verdadeo** [josdejong/jsonrepair#80]
import jsonrepair from 'jsonrepair'
^^^^^^

SyntaxError: Cannot use import statement outside a module

Code:
``import jsonrepair from 'jsonrepair'

// The following is invalid JSON: is consists of JSON contents copied from 
// a JavaScript code base, where the keys are missing double quotes, 
// and strings are using single quotes:
const json = '{name: \'John\'}'

const repaired = jsonrepair(json)
console.log(repaired) // '{"name": "John"}'``

**Comment by josdejong** [comment]
If you want to use `import` in your nodejs application, you'll have to set `"type": "module"` in the `package.json` or use the `.mjs` extension.

**Comment by josdejong** [comment]
(and if you can't or don't want to use `import` you can use `require`)
