### ISSUE TITLE
Doesn't strip unnecessary white space

### ISSUE THREAD

**Issue by garrytaulu** [josdejong/jsonrepair#87]
I'm on my phone so apologies for any odd formatting but note the " keywords" key has a leading space that doesn't get fixed. 

{
  "type": "header-block",
  "design": 0,
  "values": {
      options: {
         background: "red",
         alignment: 2,
      }
   }
   " keywords": "nice, yeah"
}

**Comment by josdejong** [comment]
Thanks for your suggestion. 

How can you determine whether leading or trailing space is unnecessary? I doubt if there is a general safe rule for that. It would be dangerous to trim spaces automatically, they could be intentional as well.

**Comment by garrytaulu** [comment]
That's true. I guess my current problem is I'm using the OpenAI api and with AI being AI it sometimes decides to add a space before the start of a keys name 😂 

That is something I can fix myself though — my main issue was with trailing commas which this solves 😁

Thanks for the reply.

**Comment by josdejong** [comment]
o wow 😂 . Yeah I'm afraid that is quite an edge case.
