### ISSUE TITLE
Repair mixed close-brackets: using } instead of ] or the other way around

### ISSUE THREAD

**Issue by karam-khanna** [josdejong/jsonrepair#88]
Hello! Was hoping you could support JSON errors that looks like this:

{"topics": ["Hallstead Jewelers", "Lake Avenue and Second Avenue", "Washington Street", "Tiffany &" }}
or
{"topics": ["Hallstead Jewelers", "Lake Avenue and Second Avenue", "Washington Street", "Tiffany &" }]

**Comment by josdejong** [comment]
Thinking about it: the library already repairs missing closing brackets, so to address this, we should probably only remove redundant close brackets (which in itself is also good: repairing `[1,2,3]]` ).

**Comment by karam-khanna** [comment]
Great! The redundant bracket thing was meant to by my second example but I
think I wrote it incorrectly but glad it made sense regardless :)

**Comment by josdejong** [comment]
This is supported now, fixed by implementing #103
