### ISSUE TITLE
Strip excess content after valid json (ChatGPT use case)

### ISSUE THREAD

**Issue by okomarov** [josdejong/jsonrepair#92]
Does this utility strip additional string content after a valid json structure? 

Very often chatGPT keeps responding with additional content even after you explicitly ask to respond with only valid JSON

**Comment by josdejong** [comment]
You can just try that out yourself in this playground: https://josdejong.github.io/jsonrepair/

In short: right now, the behavior is relatively conservative. No text is thrown away. When there is unexpected text right after the end of the document, an error is thrown (it would be unfortunate if a wrong closing bracket halfway a document would result in losing the second half of the document, instead of removing the wrong bracket). When there is multi line content after the end of the document, the document is interpreted as newline delimited and turned in an array.

**Comment by TomFrankly** [comment]
@okomarov not super relevant to this library, but I've found that if you provide an example in your system message, ChatGPT essentially never adds additional text in the response. I've gotten valid JSON 100% of the time since implementing that.

Still looking to use this library to validate my JSON just for thoroughness.

If you do need to strip out beginning/ending text, this can do it:

```
function removeNonJSONText (input) {
  const beginningBrace = input.indexOf('{')
  const endingBrace = input.lastIndexOf('}')
  const beginningBracket = input.indexOf('[')
  const endingBracket = input.lastIndexOf(']')

  const beginningIndex = Math.min(beginningBrace !== -1 ? beginningBrace : Infinity, beginningBracket !== -1 ? beginningBracket: Infinity)

  const endingIndex = Math.max(endingBrace !== -1 ? endingBrace : -Infinity, endingBracket !== -1 ? endingBracket: -Infinity)

  if (beginningIndex == Infinity || endingIndex == -1) {
    throw new Error("No JSON object or array found.")
  }

  const JSONString = input.substring(beginningIndex, endingIndex+1)

  return JSONString
}

const testJSON = `Here's a bunch of stuff before the JSON:

{
  "name": "John",
  "age": 30,
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "state": "CA",
    "zip": "12345"
  },
  "phoneNumbers": [
    {
      "type": "home",
      "number": "555-1234"
    },
    {
      "type": "work",
      "number": "555-5678"
    }
  ]
}

Here's a bunch of stuff after the JSON.`

const result = removeNonJSONText(testJSON)

console.log(result)
```

It won't handle edge cases where the beginning/ending text contains curly braces or brackets, and won't handle a response that returns multiple JSON blocks along with other text. But I'm going to use it as an insurance policy in my own code, in addition to jsonrepair.

It'll probably be best to first run a validation check on the response, and only run this function if it fails.

**Comment by okomarov** [comment]
> @okomarov not super relevant to this library, but I've found that if you provide an example in your system message, ChatGPT essentially never adds additional text in the response. I've gotten valid JSON 100% of the time since implementing that.

Super useful thanks. How realistic does the example need to be, or how minimal can it be, or it does not matter?

We’ve been doing validation and been thinking about matching braces to strip invalid content from json, so thanks for the snippet!

**Comment by TomFrankly** [comment]
@okomarov in my experience, you just need to give it an example of the kind of output you'd like. I made sure to format mine as an array, as the workflow I'm building needs to be able to extract multiple tasks from a single bit of transcribed input.

Here's the exact system message I'm using:

```
const systemMessage = `You are a natural language processor for a task management app. Your job is to take natural-language prompts and turn them into tasks. 

    You should look for task name, due date, assignee, and project. If due date or project is not present in each task's sentence, don't include it, and do not include a property for it.
    
    When you isolate a part of the prompt that represents a task, look for the word "project". If "project" is not present, do not include a project property for that task.
    
    Return dates in ISO 8601 format. If there are multiple tasks mentioned, return them as an array. If a task contains more than one date, identify the date that should be the due date. For example, the task, "I need to book a dinner for Thursday next week and I need to do that before the end of Friday" should have its due date set as Friday, not Thursday next week (in ISO 8601 format, with respect to today's date).
    
    Pay extra attention to this instruction: There must always be an assignee. If a sentence contains "I need to", set the assignee for that sentence's task as "${name}". If a sentence contains "I", "me", or other self-assigning language, and you think the speaker is assigning a task to themselves, set the assignee for that sentence's task as "${name}".
    
    You only speak in JSON. Do not write text that isn't JSON.
    
    Example prompt:
    
    "Tony needs to mount the new hair light by Saturday for the music video shoot, I need to sweep out the garage by next Tuesday, Marissa needs to book a flight to Seattle for the team retreat, and I need to talk to Dave about new sponsors."
    
    Example formatting:
    
    [
      {
        "task_name": "Mount new hair light",
        "due_date": "2023-05-06",
        "assignee": "Tony",
        "project": "Music video shoot"
      },
      {
        "task_name": "Sweep out the garage",
        "due_date": "2023-05-09",
        "assignee": "${name}"
      },
      {
        "task_name": "Book flight to Seattle",
        "assignee": "Marissa",
      },
      {
        "task_name": "Talk to Dave about new sponsors",
        "assignee": "${name}"
      }
    ]`;
```

**Comment by TomFrankly** [comment]
If it's helpful, here's my entire validate.js: https://github.com/TomFrankly/notion-voice-tasks/blob/main/src/services/validate.js

I wrote all this today, so it's likely to change. But at least for now, it has logic to strip out before/after text. Then it uses jsonrepair to do an extra double-check on the formatting of the rest of the JSON string.

**Comment by josdejong** [comment]
Thanks for the inputs Tom!

I'll close this question now, I think at least for the time being we should keep `jsonrepair` as it is, blindly cutting off a part of the JSON would be risky since you can lose a lot of information.

**Comment by TomFrankly** [comment]
Agreed. I think to do it right, you'd have to track the position of every open/close bracket and brace. My current code is an extremely blunt instrument, and even a single [ or { in the non-JSON portion of a response would break it.
