### ISSUE TITLE
undefined should not be wrapped with quotation

### ISSUE THREAD

**Issue by pond918** [josdejong/jsonrepair#93]
current behavior:
'{"key":"0.0.1","domain":undefined}' => '{"key":"0.0.1","domain":"undefined"}'

expected:
'{"key":"0.0.1","domain":undefined}' => '{"key":"0.0.1"}'

**Comment by pond918** [comment]
JSON.parse(JSON.stringify({"key":"0.0.1","domain":undefined})) goes {"key":"0.0.1"},
but of course, it would be big repair with '{"key":"0.0.1", "domain":null}', it works in my case, thank you!

**Comment by josdejong** [comment]
Fixed now in `v3.2.0`
